name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Ensure pytest is present even if requirements.txt is missing
          pip install pytest
          # Then install from requirements.txt if it exists
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Show workspace layout (debug)
        run: |
          pwd
          ls -la
          echo "--- tests dir ---"
          ls -la tests || true

      - name: Show pytest version (debug)
        run: python -m pytest --version

      - name: Run tests
        run: |
          python -m pytest -vv tests/test_hello.py --maxfail=1 --disable-warnings --junitxml=test-results.xml

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.xml
